---
# roles/launch/tasks/main.yml

- name: Launch EC2 Instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ security_groups }}"
    image: "{{ image }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ name }}"
    count: 1
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: yes
    wait: yes
  register: ec2

- name: Wait for SSH to come up
  wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 300
        state: started
  with_items: "{{ ec2.instances }}"

- name: Add new instances to host group
  add_host:
    name: "{{ item.public_ip }}"
    groups: airflow-group
  with_items: "{{ ec2.instances }}"

